/**
 * 主流 AI 大模型免费体验链接汇总
 * simpleIconSlug: SimpleIcons CDN 图标名 (https://cdn.simpleicons.org/)，null 则显示首字母
 */
export const modelCategories = [
  { id: 'global', label: '国际模型', labelEn: 'Global' },
  { id: 'china', label: '国产模型', labelEn: 'China' },
]

export const freeModels = [
  // ===== 国际模型 =====
  {
    id: 'openai',
    name: 'OpenAI',
    models: ['GPT-4o', 'GPT-4o-mini', 'o1', 'o3'],
    url: 'https://chatgpt.com/',
    description: 'ChatGPT — 全球最受欢迎的 AI 对话服务',
    descriptionEn: 'ChatGPT — The world\'s most popular AI chat service',
    color: '#74AA9C',
    simpleIconSlug: 'openai',
    category: 'global',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    models: ['Claude 3.5 Sonnet', 'Claude 3.5 Haiku', 'Claude 3 Opus'],
    url: 'https://claude.ai/',
    description: 'Claude — 注重安全与可靠的 AI 助手',
    descriptionEn: 'Claude — AI assistant focused on safety and reliability',
    color: '#CC9B7A',
    simpleIconSlug: 'anthropic',
    category: 'global',
  },
  {
    id: 'google',
    name: 'Google',
    models: ['Gemini 2.5 Pro', 'Gemini 2.0 Flash'],
    url: 'https://gemini.google.com/',
    description: 'Gemini — Google 最新多模态 AI 模型',
    descriptionEn: 'Gemini — Google\'s latest multimodal AI model',
    color: '#4285F4',
    simpleIconSlug: 'google',
    category: 'global',
  },
  {
    id: 'meta',
    name: 'Meta AI',
    models: ['Llama 4', 'Llama 3.1'],
    url: 'https://www.meta.ai/',
    description: 'Meta AI — 基于 Llama 系列的开源 AI 助手',
    descriptionEn: 'Meta AI — Open-source Llama series AI assistant',
    color: '#0064FF',
    simpleIconSlug: 'meta',
    category: 'global',
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    models: ['Mistral Large', 'Mistral Small', 'Le Chat'],
    url: 'https://chat.mistral.ai/',
    description: 'Le Chat — 高效、轻量的欧洲 AI 助手',
    descriptionEn: 'Le Chat — Efficient, lightweight European AI assistant',
    color: '#FF6B35',
    simpleIconSlug: 'mistral',
    category: 'global',
  },
  {
    id: 'grok',
    name: 'xAI',
    models: ['Grok 3'],
    url: 'https://grok.com/',
    description: 'Grok — xAI 打造的实时知识 AI',
    descriptionEn: 'Grok — Real-time knowledge AI by xAI',
    color: '#1C1C1E',
    simpleIconSlug: 'xai',
    category: 'global',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    models: ['Perplexity Pro'],
    url: 'https://www.perplexity.ai/',
    description: 'Perplexity — AI 搜索引擎，答案带引用来源',
    descriptionEn: 'Perplexity — AI search engine with cited answers',
    color: '#6366F1',
    simpleIconSlug: 'perplexity',
    category: 'global',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    models: ['Command R+', 'Command R'],
    url: 'https://coral.cohere.com/',
    description: 'Coral — 企业级 RAG 与工具调用 AI',
    descriptionEn: 'Coral — Enterprise-grade RAG and tool-use AI',
    color: '#D18EE2',
    simpleIconSlug: 'cohere',
    category: 'global',
  },
  {
    id: 'copilot',
    name: 'Microsoft Copilot',
    models: ['GPT-4', 'Copilot'],
    url: 'https://copilot.microsoft.com/',
    description: 'Copilot — 微软基于 GPT-4 的 AI 助手，免费使用',
    descriptionEn: 'Copilot — Microsoft\'s GPT-4 powered AI assistant, free to use',
    color: '#0078D4',
    simpleIconSlug: 'microsoftcopilot',
    category: 'global',
  },
  {
    id: 'huggingchat',
    name: 'Hugging Face',
    models: ['Llama 3', 'Qwen 2.5', 'Phi-4', 'Gemma'],
    url: 'https://huggingface.co/chat/',
    description: 'HuggingChat — 开源模型集合平台，完全免费',
    descriptionEn: 'HuggingChat — Open-source model hub, completely free',
    color: '#FFD21E',
    simpleIconSlug: 'huggingface',
    category: 'global',
  },
  {
    id: 'poe',
    name: 'Poe',
    models: ['GPT-4o', 'Claude', 'Gemini', 'Llama'],
    url: 'https://poe.com/',
    description: 'Poe — Quora 推出的多模型聚合平台',
    descriptionEn: 'Poe — Quora\'s multi-model aggregation platform',
    color: '#5D3FD3',
    simpleIconSlug: 'poe',
    category: 'global',
  },
  {
    id: 'characterai',
    name: 'Character.AI',
    models: ['Character AI'],
    url: 'https://character.ai/',
    description: 'Character.AI — 与 AI 角色对话的创意平台',
    descriptionEn: 'Character.AI — Creative platform for chatting with AI characters',
    color: '#6C47FF',
    simpleIconSlug: 'characterdotai',
    category: 'global',
  },
  // ===== 国产模型 =====
  {
    id: 'deepseek',
    name: 'DeepSeek',
    models: ['DeepSeek-V3', 'DeepSeek-R1'],
    url: 'https://chat.deepseek.com/',
    description: 'DeepSeek — 开源高性能推理模型',
    descriptionEn: 'DeepSeek — Open-source high-performance reasoning model',
    color: '#4F6AF0',
    simpleIconSlug: 'deepseek',
    category: 'china',
  },
  {
    id: 'ali',
    name: '阿里通义千问',
    models: ['Qwen2.5-72B', 'Qwen-Max', '通义千问'],
    url: 'https://tongyi.aliyun.com/',
    description: '通义千问 — 阿里云自研大模型，支持多模态与文档处理',
    descriptionEn: 'Tongyi Qianwen — Alibaba Cloud LLM with multimodal support',
    color: '#FF6A00',
    simpleIconSlug: 'alibabacloud',
    category: 'china',
  },
  {
    id: 'baidu',
    name: '百度文心一言',
    models: ['ERNIE 4.0', 'ERNIE 3.5'],
    url: 'https://yiyan.baidu.com/',
    description: '文心一言 — 百度自研知识增强大模型',
    descriptionEn: 'ERNIE Bot — Baidu\'s knowledge-augmented LLM',
    color: '#2932E1',
    simpleIconSlug: 'baidu',
    category: 'china',
  },
  {
    id: 'byte',
    name: '字节豆包',
    models: ['豆包 Pro', '豆包 1.5'],
    url: 'https://www.doubao.com/',
    description: '豆包 — 字节跳动自研 AI 对话助手',
    descriptionEn: 'Doubao — ByteDance\'s AI chat assistant',
    color: '#00C853',
    simpleIconSlug: 'bytedance',
    category: 'china',
  },
  {
    id: 'tencent',
    name: '腾讯混元',
    models: ['混元 Large', '混元 Standard'],
    url: 'https://hunyuan.tencent.com/',
    description: '腾讯混元 — 腾讯自研万亿参数大模型',
    descriptionEn: 'Hunyuan — Tencent\'s trillion-parameter LLM',
    color: '#0052D9',
    simpleIconSlug: 'tencentqq',
    category: 'china',
  },
  {
    id: 'kimi',
    name: '月之暗面 Kimi',
    models: ['Kimi K2', 'Kimi'],
    url: 'https://kimi.moonshot.cn/',
    description: 'Kimi — 以超长上下文窗口著称的 AI 助手',
    descriptionEn: 'Kimi — AI assistant known for ultra-long context window',
    color: '#1E90FF',
    simpleIconSlug: null,
    category: 'china',
  },
  {
    id: 'zhipu',
    name: '智谱AI',
    models: ['GLM-4-Plus', 'GLM-4-Air', 'CodeGeeX'],
    url: 'https://chatglm.cn/',
    description: '智谱清言 — 基于 GLM 系列的新一代 AI 助手',
    descriptionEn: 'ChatGLM — Next-gen AI assistant based on GLM series',
    color: '#3388FF',
    simpleIconSlug: null,
    category: 'china',
  },
  {
    id: 'yi',
    name: '零一万物 Yi',
    models: ['Yi-Lightning', 'Yi-Large'],
    url: 'https://yi.chat/',
    description: 'Yi — 零一万物打造的高性能开源大模型',
    descriptionEn: 'Yi — High-performance open-source LLM by 01.AI',
    color: '#0057FF',
    simpleIconSlug: null,
    category: 'china',
  },
  {
    id: 'baichuan',
    name: '百川智能',
    models: ['Baichuan 4', 'Baichuan 3'],
    url: 'https://www.baichuan-ai.com/chat',
    description: '百川 — 百川智能自研大模型，擅长医疗与法律领域',
    descriptionEn: 'Baichuan — LLM specialized in medical and legal domains',
    color: '#4A90D9',
    simpleIconSlug: null,
    category: 'china',
  },
  {
    id: 'spark',
    name: '讯飞星火',
    models: ['星火 4.0', '星火 3.5'],
    url: 'https://xinghuo.xfyun.cn/',
    description: '星火 — 科大讯飞自研大模型，语音交互能力突出',
    descriptionEn: 'Spark — iFlytek\'s LLM with exceptional voice interaction',
    color: '#FF6600',
    simpleIconSlug: 'iflytek',
    category: 'china',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    models: ['MiniMax-Text-01', 'MiniMax-VL'],
    url: 'https://agent.minimaxi.com/',
    description: '海螺AI — MiniMax 自研多模态 AI 助手',
    descriptionEn: 'Hailuo AI — MiniMax\'s multimodal AI assistant',
    color: '#7C3AED',
    simpleIconSlug: null,
    category: 'china',
  },
  {
    id: 'step',
    name: '阶跃星辰',
    models: ['Step-2', 'Step-1'],
    url: 'https://stepchat.cn/',
    description: 'Step — 阶跃星辰自研大模型，推理能力出色',
    descriptionEn: 'Step — LLM with outstanding reasoning capabilities',
    color: '#1677FF',
    simpleIconSlug: null,
    category: 'china',
  },
  {
    id: 'skytime',
    name: '昆仑万维天工',
    models: ['天工 4.0', '天工 3.5'],
    url: 'https://www.tiangong.cn/',
    description: '天工 — 昆仑万维自研大模型，支持搜索增强生成',
    descriptionEn: 'Skywork — LLM with search-enhanced generation',
    color: '#E60012',
    simpleIconSlug: null,
    category: 'china',
  },
  {
    id: 'sensetime',
    name: '商汤日日新',
    models: ['SenseChat 5.0', 'SenseChat'],
    url: 'https://chat.sensetime.com/',
    description: '日日新 — 商汤科技自研大模型，视觉理解领先',
    descriptionEn: 'SenseChat — SenseTime\'s LLM with leading visual understanding',
    color: '#ED1C24',
    simpleIconSlug: 'sensetime',
    category: 'china',
  },
  {
    id: 'siliconflow',
    name: '硅基流动',
    models: ['DeepSeek-V3', 'Qwen2.5', 'GLM-4', 'Llama 3'],
    url: 'https://cloud.siliconflow.cn/',
    description: 'SiliconFlow — 一站式模型 API 平台，汇集主流开源模型',
    descriptionEn: 'SiliconFlow — One-stop model API platform with popular open-source models',
    color: '#2B6EFC',
    simpleIconSlug: null,
    category: 'china',
  },
  {
    id: 'yuanbao',
    name: '腾讯元宝',
    models: ['元宝', '混元'],
    url: 'https://yuanbao.tencent.com/',
    description: '元宝 — 腾讯面向消费者的 AI 对话应用',
    descriptionEn: 'Yuanbao — Tencent\'s consumer-facing AI chat app',
    color: '#0CBF75',
    simpleIconSlug: 'tencentqq',
    category: 'china',
  },
  {
    id: 'ai360',
    name: '360 智脑',
    models: ['360智脑 4.0'],
    url: 'https://ai.360.com/',
    description: '360 智脑 — 360 集团自研大模型，安全与搜索能力突出',
    descriptionEn: '360 Brain — 360\'s LLM with strong security and search capabilities',
    color: '#E60012',
    simpleIconSlug: 'qihoo360',
    category: 'china',
  },
  {
    id: 'xiaoyi',
    name: '华为小艺',
    models: ['盘古', '小艺'],
    url: 'https://xiaoyi.huawei.com/',
    description: '小艺 — 华为盘古大模型驱动的智能助手',
    descriptionEn: 'Xiaoyi — Huawei\'s Pangu model-powered smart assistant',
    color: '#CF0A2C',
    simpleIconSlug: 'huawei',
    category: 'china',
  },
]

/**
 * 获取特定模型类型的免费体验链接
 */
export function getModelFreeUrl(modelType) {
  const mapping = {
    openai: 'https://chatgpt.com/',
    anthropic: 'https://claude.ai/',
    deepseek: 'https://chat.deepseek.com/',
    ali: 'https://tongyi.aliyun.com/',
    baidu: 'https://yiyan.baidu.com/',
    byte: 'https://www.doubao.com/',
    tencent: 'https://hunyuan.tencent.com/',
    minimax: 'https://agent.minimaxi.com/',
    moonshot: 'https://kimi.moonshot.cn/',
    kimi: 'https://kimi.moonshot.cn/',
    zhipu: 'https://chatglm.cn/',
    yi: 'https://yi.chat/',
    baichuan: 'https://www.baichuan-ai.com/chat',
    spark: 'https://xinghuo.xfyun.cn/',
    google: 'https://gemini.google.com/',
    mistral: 'https://chat.mistral.ai/',
    grok: 'https://grok.com/',
    copilot: 'https://copilot.microsoft.com/',
    huggingchat: 'https://huggingface.co/chat/',
    poe: 'https://poe.com/',
    characterai: 'https://character.ai/',
    yuanbao: 'https://yuanbao.tencent.com/',
    ai360: 'https://ai.360.com/',
    xiaoyi: 'https://xiaoyi.huawei.com/',
  }
  return mapping[modelType] || null
}
